/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Perfume_Finale.gltf')

  let sum = 85
  let groups

  let modelText = []
  const propsText = props.name.cyberName
  const aZ = new RegExp('^[a-zA-Z*]+$')
  const numbers = new RegExp('^[0-9$#!&]+$')

  if (propsText) {
    modelText = propsText.substr(0, 5).split('')
  }

  useEffect(() => {

  })

  if (modelText && modelText.length > 0) {
    groups = modelText.map((a, i) => {
      if (aZ.test(a)) {
        return (
          <group key={i} position={[0, `${i > 0 ? (sum += -9) : 85}`, 16, 6]}>
            <mesh
              geometry={nodes[`${a.toUpperCase()}-Local`].geometry}
              material={materials[`${a.toLowerCase()}-Material`]}
            />
          </group>
        )
      } else if (numbers.test(a)) {
        return (
          <group key={i} position={[0, `${i > 0 ? (sum += -9) : 85}`, 16, 6]}>
            <mesh
              geometry={nodes[`${a.toUpperCase()}-Local_1`].geometry}
              material={materials[`${a.toLowerCase()}-Material`]}
            />
          </group>
        )
      }
      return '';
    })
  }
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
        <group position={[0, 101, -1]} >
          <mesh
            geometry={nodes['do1-Local'].geometry}
            material={nodes['do1-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['dot2-Local'].geometry}
            material={nodes['dot2-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['dot3-Local'].geometry}
            material={nodes['dot3-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['dot4-Local'].geometry}
            material={nodes['dot4-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['dot5-Local'].geometry}
            material={nodes['dot5-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['dot6-Local'].geometry}
            material={nodes['dot6-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['dot7-Local'].geometry}
            material={nodes['dot7-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['dot8-Local'].geometry}
            material={nodes['dot8-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['dot9-Local'].geometry}
            material={nodes['dot9-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['dot10-Local'].geometry}
            material={nodes['dot10-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['dot11-Local'].geometry}
            material={nodes['dot11-Local'].material}
            position={[-15.5, 0.5, -15.5]}
          />
          <mesh
            geometry={nodes['spray1-Local_1'].geometry}
            material={materials['spray1-Material']}
            position={[0, 7.5, 0.5]}
          />
        </group>
        <group position={[0, 111, 0]}>
          <group position={[0, 5, 0]}>
            <mesh
              name="spray2-Local_1"
              geometry={nodes['spray2-Local_1'].geometry}
              material={materials['spray2-Material']}
              position={[0, 4.5, 0]}
            />
          </group>
        </group>

        <group position={[-1, 32, 16]}>
          <mesh
            geometry={nodes['icons-Local_1'].geometry}
            material={materials['icons-Material']}
            position={[0.5, 5.5, 0.5]}
          />
        </group>
        <mesh
          geometry={nodes['cyber_final-Local_1'].geometry}
          material={materials['cyber_final-Material']}
          position={[0, 51, 0.5]}
        />

        {/* here groups start */}
        {groups}
        {/* groups end */}

        <group position={[0, 80, 15]} />
        <group position={[0, 80, 15]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Perfume_Finale.gltf')